### PR TITLE
fix(tasks.extract_from_html): Catch UnicodeDecodeError

### PR DESCRIPTION
**Pull request by grossir**
UnicodeDecodeError was bubbling because except clause was not catching it

Solves #181

### CODE REVIEW

**Review by mlissner — COMMENTED** [review]
Seems fine. Do we need the DoctorUnicodeDecodeError anymore?

**Review by flooie — APPROVED** [review]
Thanks @grossir

**Comment by flooie** [comment]
@mlissner - sorry to get in the way of this.

**Comment by mlissner** [comment]
We passed like ships in the night! My thought was that if we want to remove it — you tell me — I could do it and then we'd know if my magic powers fix the deployment workflow.

**Comment by flooie** [comment]
I say let it disappear into the ether.

**Comment by mlissner** [comment]
Hm, there's something interesting (clever?) going on here: 

https://github.com/freelawproject/doctor/blob/adf391227995a1360d673f07258e9ce1af5f51e4/doctor/lib/utils.py#L93-L95

Hm...I don't have time to think through if we want to remove that or if it's doing something useful, but happy to do what you say.

**Pull request merged**
