### PR TITLE
fix(tasks): Encode bytes correctly in extract html

### PR DESCRIPTION
**Pull request by flooie**
Extract HTML had some ... python2-esque encoding
going on.  This fix should resolve some bad encoding
that was going on and HTML extraction

### CODE REVIEW

**Comment by flooie** [comment]
This got unfortunately held up by a mismatch with the new seal-rookery.

**Comment by flooie** [comment]
This is a small tweak to open HTML files with proper encoding.

**Comment by mlissner** [comment]
Ah, right. My fault. I harmonized the seal and portraits repos to both use search. Should have remembered to update CL.

**Comment by flooie** [comment]
Should've seen it earlier.  Thanks for harmonizing it

**Pull request merged**
